#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : librdkafka
Version  : 1.5.0
Release  : 3
URL      : https://github.com/edenhill/librdkafka/archive/v1.5.0/librdkafka-1.5.0.tar.gz
Source0  : https://github.com/edenhill/librdkafka/archive/v1.5.0/librdkafka-1.5.0.tar.gz
Summary  : The Apache Kafka C library
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause ISC MIT Zlib
Requires: librdkafka-data = %{version}-%{release}
Requires: librdkafka-lib = %{version}-%{release}
Requires: librdkafka-license = %{version}-%{release}
Requires: boto3
BuildRequires : boto3
BuildRequires : buildreq-cmake
BuildRequires : glibc-dev
BuildRequires : openssl-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(liblz4)
BuildRequires : pkgconfig(libsasl2)
BuildRequires : pkgconfig(libzstd)
BuildRequires : zlib-dev

%description
librdkafka is the C/C++ client library implementation of the Apache Kafka protocol, containing both Producer and Consumer support.

%package data
Summary: data components for the librdkafka package.
Group: Data

%description data
data components for the librdkafka package.


%package dev
Summary: dev components for the librdkafka package.
Group: Development
Requires: librdkafka-lib = %{version}-%{release}
Requires: librdkafka-data = %{version}-%{release}
Provides: librdkafka-devel = %{version}-%{release}
Requires: librdkafka = %{version}-%{release}

%description dev
dev components for the librdkafka package.


%package lib
Summary: lib components for the librdkafka package.
Group: Libraries
Requires: librdkafka-data = %{version}-%{release}
Requires: librdkafka-license = %{version}-%{release}

%description lib
lib components for the librdkafka package.


%package license
Summary: license components for the librdkafka package.
Group: Default

%description license
license components for the librdkafka package.


%prep
%setup -q -n librdkafka-1.5.0
cd %{_builddir}/librdkafka-1.5.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1601863451
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make  %{?_smp_mflags}
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test || :

%install
export SOURCE_DATE_EPOCH=1601863451
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/librdkafka
cp %{_builddir}/librdkafka-1.5.0/LICENSE %{buildroot}/usr/share/package-licenses/librdkafka/5ff2577ff9af97666d8a53d5d050f59f523697b9
cp %{_builddir}/librdkafka-1.5.0/LICENSE.crc32c %{buildroot}/usr/share/package-licenses/librdkafka/1c729ec87a41f94eabbabb496454e54cf770c678
cp %{_builddir}/librdkafka-1.5.0/LICENSE.hdrhistogram %{buildroot}/usr/share/package-licenses/librdkafka/25c13cb8c65676499760570c0bb60538e34c6b90
cp %{_builddir}/librdkafka-1.5.0/LICENSE.lz4 %{buildroot}/usr/share/package-licenses/librdkafka/a4e718c02da9df0bc7fa137d001387bb264a3c90
cp %{_builddir}/librdkafka-1.5.0/LICENSE.murmur2 %{buildroot}/usr/share/package-licenses/librdkafka/199b0086de98cc0044deeedf89a7f819c9f9a5ce
cp %{_builddir}/librdkafka-1.5.0/LICENSE.pycrc %{buildroot}/usr/share/package-licenses/librdkafka/e8651e180555376b5c2b5ecd114981481a512546
cp %{_builddir}/librdkafka-1.5.0/LICENSE.queue %{buildroot}/usr/share/package-licenses/librdkafka/7f653fbf85dbdf0f48138299d18381a6bfb101f1
cp %{_builddir}/librdkafka-1.5.0/LICENSE.snappy %{buildroot}/usr/share/package-licenses/librdkafka/7e81b2429a98f39ef348b68a40eaac4b834f29a7
cp %{_builddir}/librdkafka-1.5.0/LICENSE.tinycthread %{buildroot}/usr/share/package-licenses/librdkafka/14107287e77706772572744b1b3ecfde8960472d
cp %{_builddir}/librdkafka-1.5.0/LICENSE.wingetopt %{buildroot}/usr/share/package-licenses/librdkafka/e612d1fbaad7c0a278b025734f37cfa6bbb0b678
cp %{_builddir}/librdkafka-1.5.0/LICENSES.txt %{buildroot}/usr/share/package-licenses/librdkafka/39036f7eddefadc999d0ffb284f0f3b74c9c4142
cp %{_builddir}/librdkafka-1.5.0/packaging/cmake/Modules/LICENSE.FindZstd %{buildroot}/usr/share/package-licenses/librdkafka/b5ec887319537fbea3fa9804ac9a5cd5e40afd2e
cp %{_builddir}/librdkafka-1.5.0/packaging/debian/copyright %{buildroot}/usr/share/package-licenses/librdkafka/307a3e7eaead9b95961a1293d0352d9afd8c98c4
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/licenses/librdkafka/LICENSES.txt

%files dev
%defattr(-,root,root,-)
/usr/include/librdkafka/rdkafka.h
/usr/include/librdkafka/rdkafka_mock.h
/usr/include/librdkafka/rdkafkacpp.h
/usr/lib/cmake/RdKafka/FindLZ4.cmake
/usr/lib/cmake/RdKafka/RdKafkaConfig.cmake
/usr/lib/cmake/RdKafka/RdKafkaConfigVersion.cmake
/usr/lib/cmake/RdKafka/RdKafkaTargets-relwithdebinfo.cmake
/usr/lib/cmake/RdKafka/RdKafkaTargets.cmake
/usr/lib64/librdkafka++.so
/usr/lib64/librdkafka.so
/usr/lib64/pkgconfig/rdkafka++.pc
/usr/lib64/pkgconfig/rdkafka.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/librdkafka++.so.1
/usr/lib64/librdkafka.so.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/librdkafka/14107287e77706772572744b1b3ecfde8960472d
/usr/share/package-licenses/librdkafka/199b0086de98cc0044deeedf89a7f819c9f9a5ce
/usr/share/package-licenses/librdkafka/1c729ec87a41f94eabbabb496454e54cf770c678
/usr/share/package-licenses/librdkafka/25c13cb8c65676499760570c0bb60538e34c6b90
/usr/share/package-licenses/librdkafka/307a3e7eaead9b95961a1293d0352d9afd8c98c4
/usr/share/package-licenses/librdkafka/39036f7eddefadc999d0ffb284f0f3b74c9c4142
/usr/share/package-licenses/librdkafka/5ff2577ff9af97666d8a53d5d050f59f523697b9
/usr/share/package-licenses/librdkafka/7e81b2429a98f39ef348b68a40eaac4b834f29a7
/usr/share/package-licenses/librdkafka/7f653fbf85dbdf0f48138299d18381a6bfb101f1
/usr/share/package-licenses/librdkafka/a4e718c02da9df0bc7fa137d001387bb264a3c90
/usr/share/package-licenses/librdkafka/b5ec887319537fbea3fa9804ac9a5cd5e40afd2e
/usr/share/package-licenses/librdkafka/e612d1fbaad7c0a278b025734f37cfa6bbb0b678
/usr/share/package-licenses/librdkafka/e8651e180555376b5c2b5ecd114981481a512546
