#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : librdkafka
Version  : 1.2.0
Release  : 1
URL      : https://github.com/edenhill/librdkafka/archive/v1.2.0.tar.gz
Source0  : https://github.com/edenhill/librdkafka/archive/v1.2.0.tar.gz
Summary  : The Apache Kafka C library
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause ISC MIT Zlib
Requires: librdkafka-data = %{version}-%{release}
Requires: librdkafka-lib = %{version}-%{release}
Requires: librdkafka-license = %{version}-%{release}
Requires: boto3
BuildRequires : boto3
BuildRequires : buildreq-cmake
BuildRequires : glibc-dev
BuildRequires : openssl-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(liblz4)
BuildRequires : pkgconfig(libsasl2)
BuildRequires : pkgconfig(libzstd)
BuildRequires : zlib-dev

%description
librdkafka is the C/C++ client library implementation of the Apache Kafka protocol, containing both Producer and Consumer support.

%package data
Summary: data components for the librdkafka package.
Group: Data

%description data
data components for the librdkafka package.


%package dev
Summary: dev components for the librdkafka package.
Group: Development
Requires: librdkafka-lib = %{version}-%{release}
Requires: librdkafka-data = %{version}-%{release}
Provides: librdkafka-devel = %{version}-%{release}
Requires: librdkafka = %{version}-%{release}

%description dev
dev components for the librdkafka package.


%package lib
Summary: lib components for the librdkafka package.
Group: Libraries
Requires: librdkafka-data = %{version}-%{release}
Requires: librdkafka-license = %{version}-%{release}

%description lib
lib components for the librdkafka package.


%package license
Summary: license components for the librdkafka package.
Group: Default

%description license
license components for the librdkafka package.


%prep
%setup -q -n librdkafka-1.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1569345318
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make  %{?_smp_mflags}  VERBOSE=1
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test || :

%install
export SOURCE_DATE_EPOCH=1569345318
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/librdkafka
cp LICENSE %{buildroot}/usr/share/package-licenses/librdkafka/LICENSE
cp LICENSE.crc32c %{buildroot}/usr/share/package-licenses/librdkafka/LICENSE.crc32c
cp LICENSE.hdrhistogram %{buildroot}/usr/share/package-licenses/librdkafka/LICENSE.hdrhistogram
cp LICENSE.lz4 %{buildroot}/usr/share/package-licenses/librdkafka/LICENSE.lz4
cp LICENSE.murmur2 %{buildroot}/usr/share/package-licenses/librdkafka/LICENSE.murmur2
cp LICENSE.pycrc %{buildroot}/usr/share/package-licenses/librdkafka/LICENSE.pycrc
cp LICENSE.queue %{buildroot}/usr/share/package-licenses/librdkafka/LICENSE.queue
cp LICENSE.snappy %{buildroot}/usr/share/package-licenses/librdkafka/LICENSE.snappy
cp LICENSE.tinycthread %{buildroot}/usr/share/package-licenses/librdkafka/LICENSE.tinycthread
cp LICENSE.wingetopt %{buildroot}/usr/share/package-licenses/librdkafka/LICENSE.wingetopt
cp LICENSES.txt %{buildroot}/usr/share/package-licenses/librdkafka/LICENSES.txt
cp debian/copyright %{buildroot}/usr/share/package-licenses/librdkafka/debian_copyright
cp packaging/cmake/Modules/LICENSE.FindZstd %{buildroot}/usr/share/package-licenses/librdkafka/packaging_cmake_Modules_LICENSE.FindZstd
cp packaging/debian/copyright %{buildroot}/usr/share/package-licenses/librdkafka/packaging_debian_copyright
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/licenses/librdkafka/LICENSES.txt

%files dev
%defattr(-,root,root,-)
/usr/include/librdkafka/rdkafka.h
/usr/include/librdkafka/rdkafkacpp.h
/usr/lib/cmake/RdKafka/FindLZ4.cmake
/usr/lib/cmake/RdKafka/RdKafkaConfig.cmake
/usr/lib/cmake/RdKafka/RdKafkaConfigVersion.cmake
/usr/lib/cmake/RdKafka/RdKafkaTargets-relwithdebinfo.cmake
/usr/lib/cmake/RdKafka/RdKafkaTargets.cmake
/usr/lib64/librdkafka++.so
/usr/lib64/librdkafka.so
/usr/lib64/pkgconfig/rdkafka++.pc
/usr/lib64/pkgconfig/rdkafka.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/librdkafka++.so.1
/usr/lib64/librdkafka.so.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/librdkafka/LICENSE
/usr/share/package-licenses/librdkafka/LICENSE.crc32c
/usr/share/package-licenses/librdkafka/LICENSE.hdrhistogram
/usr/share/package-licenses/librdkafka/LICENSE.lz4
/usr/share/package-licenses/librdkafka/LICENSE.murmur2
/usr/share/package-licenses/librdkafka/LICENSE.pycrc
/usr/share/package-licenses/librdkafka/LICENSE.queue
/usr/share/package-licenses/librdkafka/LICENSE.snappy
/usr/share/package-licenses/librdkafka/LICENSE.tinycthread
/usr/share/package-licenses/librdkafka/LICENSE.wingetopt
/usr/share/package-licenses/librdkafka/LICENSES.txt
/usr/share/package-licenses/librdkafka/debian_copyright
/usr/share/package-licenses/librdkafka/packaging_cmake_Modules_LICENSE.FindZstd
/usr/share/package-licenses/librdkafka/packaging_debian_copyright
